program TokenUniverse;

uses
  Vcl.Forms,
  TU.Tokens in 'Core\TU.Tokens.pas',
  UI.TokenListFrame in 'UI\UI.TokenListFrame.pas' {FrameTokenList: TFrame},
  UI.MainForm in 'UI\UI.MainForm.pas' {FormMain},
  UI.Modal.AccessAndType in 'UI\UI.Modal.AccessAndType.pas' {DialogAccessAndType},
  UI.HandleSearch in 'UI\UI.HandleSearch.pas' {FormHandleSearch},
  UI.Information in 'UI\UI.Information.pas' {InfoDialog},
  UI.ProcessList in 'UI\UI.ProcessList.pas' {ProcessListDialog},
  TU.RestartSvc in 'Core\TU.RestartSvc.pas',
  TU.Suggestions in 'Core\TU.Suggestions.pas',
  UI.Restrict in 'UI\UI.Restrict.pas' {DialogRestrictToken},
  UI.Prototypes in 'UI\UI.Prototypes.pas',
  TU.Credentials in 'Core\TU.Credentials.pas',
  UI.Modal.Logon in 'UI\UI.Modal.Logon.pas' {LogonDialog},
  UI.Modal.PickUser in 'UI\UI.Modal.PickUser.pas' {DialogPickUser},
  TU.ObjPicker in 'Core\TU.ObjPicker.pas',
  UI.CreateToken in 'UI\UI.CreateToken.pas' {DialogCreateToken},
  TU.Tokens.Types in 'Core\TU.Tokens.Types.pas',
  UI.Modal.Columns in 'UI\UI.Modal.Columns.pas' {DialogColumns},
  UI.Settings in 'UI\UI.Settings.pas',
  UI.Modal.Access in 'UI\UI.Modal.Access.pas' {DialogAccess},
  UI.Modal.ComboDlg in 'UI\UI.Modal.ComboDlg.pas' {ComboDialog},
  TU.Winapi in 'Core\TU.Winapi.pas',
  UI.Modal.ThreadList in 'UI\UI.Modal.ThreadList.pas' {ThreadListDialog},
  UI.Information.Access in 'UI\UI.Information.Access.pas' {DialogGrantedAccess},
  UI.Modal.PickToken in 'UI\UI.Modal.PickToken.pas' {DialogPickToken},
  UI.New.Safer in 'UI\UI.New.Safer.pas' {DialogSafer},
  UI.Prototypes.AuditFrame in 'UI\UI.Prototypes.AuditFrame.pas' {FrameAudit: TFrame},
  UI.Prototypes.Logon in 'UI\UI.Prototypes.Logon.pas' {FrameLogon: TFrame},
  UI.Sid.View in 'UI\UI.Sid.View.pas' {DialogSidView},
  UI.Prototypes.Lsa.Rights in 'UI\UI.Prototypes.Lsa.Rights.pas' {FrameLsaRights: TFrame},
  UI.Prototypes.Lsa.Privileges in 'UI\UI.Prototypes.Lsa.Privileges.pas' {FrameLsaPrivileges: TFrame},
  UI.Audit.System in 'UI\UI.Audit.System.pas' {DialogSystemAudit},
  UI.Process.Run in 'UI\UI.Process.Run.pas' {DialogRun},
  VclEx.ListView in 'NtUtilsUI\VclEx\VclEx.ListView.pas',
  Ntapi.ntdbg in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntdbg.pas',
  Ntapi.ntdef in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntdef.pas',
  Ntapi.ntexapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntexapi.pas',
  Ntapi.ntioapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntioapi.pas',
  Ntapi.ntkeapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntkeapi.pas',
  Ntapi.ntldr in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntldr.pas',
  Ntapi.ntlpcapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntlpcapi.pas',
  Ntapi.ntmmapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntmmapi.pas',
  Ntapi.ntobapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntobapi.pas',
  Ntapi.ntpebteb in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntpebteb.pas',
  Ntapi.ntpsapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntpsapi.pas',
  Ntapi.ntregapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntregapi.pas',
  Ntapi.ntrtl in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntrtl.pas',
  Ntapi.ntsam in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntsam.pas',
  Ntapi.ntseapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntseapi.pas',
  Ntapi.ntstatus in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntstatus.pas',
  Ntapi.nttmapi in 'NtUtilsUI\NtUtils\Headers\Ntapi.nttmapi.pas',
  Ntapi.ntwow64 in 'NtUtilsUI\NtUtils\Headers\Ntapi.ntwow64.pas',
  Winapi.ConsoleApi in 'NtUtilsUI\NtUtils\Headers\Winapi.ConsoleApi.pas',
  Winapi.ntlsa in 'NtUtilsUI\NtUtils\Headers\Winapi.ntlsa.pas',
  Winapi.NtSecApi in 'NtUtilsUI\NtUtils\Headers\Winapi.NtSecApi.pas',
  Winapi.ProcessThreadsApi in 'NtUtilsUI\NtUtils\Headers\Winapi.ProcessThreadsApi.pas',
  Winapi.Sddl in 'NtUtilsUI\NtUtils\Headers\Winapi.Sddl.pas',
  Winapi.securitybaseapi in 'NtUtilsUI\NtUtils\Headers\Winapi.securitybaseapi.pas',
  Winapi.Shell in 'NtUtilsUI\NtUtils\Headers\Winapi.Shell.pas',
  Winapi.Shlwapi in 'NtUtilsUI\NtUtils\Headers\Winapi.Shlwapi.pas',
  Winapi.Svc in 'NtUtilsUI\NtUtils\Headers\Winapi.Svc.pas',
  Winapi.UserEnv in 'NtUtilsUI\NtUtils\Headers\Winapi.UserEnv.pas',
  Winapi.Wdc in 'NtUtilsUI\NtUtils\Headers\Winapi.Wdc.pas',
  Winapi.WinBase in 'NtUtilsUI\NtUtils\Headers\Winapi.WinBase.pas',
  Winapi.WinError in 'NtUtilsUI\NtUtils\Headers\Winapi.WinError.pas',
  Winapi.WinNt in 'NtUtilsUI\NtUtils\Headers\Winapi.WinNt.pas',
  Winapi.WinSafer in 'NtUtilsUI\NtUtils\Headers\Winapi.WinSafer.pas',
  Winapi.winsta in 'NtUtilsUI\NtUtils\Headers\Winapi.winsta.pas',
  Winapi.WinUser in 'NtUtilsUI\NtUtils\Headers\Winapi.WinUser.pas',
  DelphiUtils.Arrays in 'NtUtilsUI\NtUtils\DelphiUtils.Arrays.pas',
  DelphiUtils.Events in 'NtUtilsUI\NtUtils\DelphiUtils.Events.pas',
  NtUtils.Debug in 'NtUtilsUI\NtUtils\NtUtils.Debug.pas',
  NtUtils.Environment in 'NtUtilsUI\NtUtils\NtUtils.Environment.pas',
  NtUtils.Files in 'NtUtilsUI\NtUtils\NtUtils.Files.pas',
  NtUtils.Job in 'NtUtilsUI\NtUtils\NtUtils.Job.pas',
  NtUtils.Ldr in 'NtUtilsUI\NtUtils\NtUtils.Ldr.pas',
  NtUtils.Lsa.Audit in 'NtUtilsUI\NtUtils\NtUtils.Lsa.Audit.pas',
  NtUtils.Lsa.Logon in 'NtUtilsUI\NtUtils\NtUtils.Lsa.Logon.pas',
  NtUtils.Lsa in 'NtUtilsUI\NtUtils\NtUtils.Lsa.pas',
  NtUtils.Lsa.Sid in 'NtUtilsUI\NtUtils\NtUtils.Lsa.Sid.pas',
  NtUtils.Objects.Compare in 'NtUtilsUI\NtUtils\NtUtils.Objects.Compare.pas',
  NtUtils.Objects.Namespace in 'NtUtilsUI\NtUtils\NtUtils.Objects.Namespace.pas',
  NtUtils.Objects in 'NtUtilsUI\NtUtils\NtUtils.Objects.pas',
  NtUtils.Objects.Snapshots in 'NtUtilsUI\NtUtils\NtUtils.Objects.Snapshots.pas',
  NtUtils.Processes.Memory in 'NtUtilsUI\NtUtils\NtUtils.Processes.Memory.pas',
  NtUtils.Processes in 'NtUtilsUI\NtUtils\NtUtils.Processes.pas',
  NtUtils.Processes.Snapshots in 'NtUtilsUI\NtUtils\NtUtils.Processes.Snapshots.pas',
  NtUtils.Profiles in 'NtUtilsUI\NtUtils\NtUtils.Profiles.pas',
  NtUtils.Registry.HKCU in 'NtUtilsUI\NtUtils\NtUtils.Registry.HKCU.pas',
  NtUtils.Registry in 'NtUtilsUI\NtUtils\NtUtils.Registry.pas',
  NtUtils.Sam in 'NtUtilsUI\NtUtils\NtUtils.Sam.pas',
  NtUtils.Sections in 'NtUtilsUI\NtUtils\NtUtils.Sections.pas',
  NtUtils.Security.Acl in 'NtUtilsUI\NtUtils\NtUtils.Security.Acl.pas',
  NtUtils.Security.AppContainer in 'NtUtilsUI\NtUtils\NtUtils.Security.AppContainer.pas',
  NtUtils.Security.Sid in 'NtUtilsUI\NtUtils\NtUtils.Security.Sid.pas',
  NtUtils.Shellcode in 'NtUtilsUI\NtUtils\NtUtils.Shellcode.pas',
  NtUtils.Svc in 'NtUtilsUI\NtUtils\NtUtils.Svc.pas',
  NtUtils.Svc.SingleTaskSvc in 'NtUtilsUI\NtUtils\NtUtils.Svc.SingleTaskSvc.pas',
  NtUtils.Threads in 'NtUtilsUI\NtUtils\NtUtils.Threads.pas',
  NtUtils.Threads.Stack in 'NtUtilsUI\NtUtils\NtUtils.Threads.Stack.pas',
  NtUtils.Tokens.Impersonate in 'NtUtilsUI\NtUtils\NtUtils.Tokens.Impersonate.pas',
  NtUtils.Tokens.Logon in 'NtUtilsUI\NtUtils\NtUtils.Tokens.Logon.pas',
  NtUtils.Tokens.Misc in 'NtUtilsUI\NtUtils\NtUtils.Tokens.Misc.pas',
  NtUtils.Tokens in 'NtUtilsUI\NtUtils\NtUtils.Tokens.pas',
  NtUtils.Tokens.Query in 'NtUtilsUI\NtUtils\NtUtils.Tokens.Query.pas',
  NtUtils.Transactions in 'NtUtilsUI\NtUtils\NtUtils.Transactions.pas',
  NtUtils.Transactions.Remote in 'NtUtilsUI\NtUtils\NtUtils.Transactions.Remote.pas',
  NtUtils.WinSafer in 'NtUtilsUI\NtUtils\NtUtils.WinSafer.pas',
  NtUtils.WinStation in 'NtUtilsUI\NtUtils\NtUtils.WinStation.pas',
  NtUtils.WinUser in 'NtUtilsUI\NtUtils\NtUtils.WinUser.pas',
  NtUtils.WinUser.WinstaLock in 'NtUtilsUI\NtUtils\NtUtils.WinUser.WinstaLock.pas',
  NtUiLib.Exceptions in 'NtUtilsUI\NtUtils\NtUiLib\NtUiLib.Exceptions.pas',
  DelphiUtils.AutoObject in 'NtUtilsUI\NtUtils\DelphiUtils.AutoObject.pas',
  DelphiApi.Reflection in 'NtUtilsUI\NtUtils\Headers\DelphiApi.Reflection.pas',
  DelphiUtils.ExternalImport in 'NtUtilsUI\NtUtils\DelphiUtils.ExternalImport.pas',
  NtUtils.Version in 'NtUtilsUI\NtUtils\Headers\NtUtils.Version.pas',
  NtUtils.ImageHlp in 'NtUtilsUI\NtUtils\NtUtils.ImageHlp.pas',
  NtUtils in 'NtUtilsUI\NtUtils\NtUtils.pas',
  NtUtils.SysUtils in 'NtUtilsUI\NtUtils\NtUtils.SysUtils.pas',
  NtUtils.Processes.Query in 'NtUtilsUI\NtUtils\NtUtils.Processes.Query.pas',
  NtUtils.System in 'NtUtilsUI\NtUtils\NtUtils.System.pas',
  DelphiUiLib.Strings in 'NtUtilsUI\NtUtils\NtUiLib\DelphiUiLib.Strings.pas',
  UI.Prototypes.Forms in 'NtUtilsUI\Common\UI.Prototypes.Forms.pas',
  VclEx.Form in 'NtUtilsUI\VclEx\VclEx.Form.pas',
  UI.Prototypes.Privileges in 'NtUtilsUI\Prototypes\UI.Prototypes.Privileges.pas' {PrivilegesFrame: TFrame},
  UI.Colors in 'NtUtilsUI\Common\UI.Colors.pas',
  UI.Prototypes.Groups in 'NtUtilsUI\Prototypes\UI.Prototypes.Groups.pas' {GroupsFrame: TFrame},
  UI.ProcessIcons in 'NtUtilsUI\Common\UI.ProcessIcons.pas',
  UI.Prototypes.AccessMask in 'NtUtilsUI\Prototypes\UI.Prototypes.AccessMask.pas' {AccessMaskFrame: TFrame},
  UI.AppContainer.View in 'UI\UI.AppContainer.View.pas' {DialogAppContainer},
  Winapi.ObjBase in 'NtUtilsUI\NtUtils\Headers\Winapi.ObjBase.pas',
  Winapi.ObjIdl in 'NtUtilsUI\NtUtils\Headers\Winapi.ObjIdl.pas',
  NtUtils.Com.Dispatch in 'NtUtilsUI\NtUtils\NtUtils.Com.Dispatch.pas',
  NtUtils.Processes.Create.Native in 'NtUtilsUI\NtUtils\NtUtils.Processes.Create.Native.pas',
  NtUtils.Processes.Create in 'NtUtilsUI\NtUtils\NtUtils.Processes.Create.pas',
  NtUtils.Processes.Create.Shell in 'NtUtilsUI\NtUtils\NtUtils.Processes.Create.Shell.pas',
  NtUtils.Processes.Create.Wdc in 'NtUtilsUI\NtUtils\NtUtils.Processes.Create.Wdc.pas',
  NtUtils.Processes.Create.Win32 in 'NtUtilsUI\NtUtils\NtUtils.Processes.Create.Win32.pas',
  NtUtils.Processes.Create.Wmi in 'NtUtilsUI\NtUtils\NtUtils.Processes.Create.Wmi.pas',
  TU.Exec in 'Core\TU.Exec.pas',
  UI.AppContainer.List in 'UI\UI.AppContainer.List.pas' {DialogACProfiles},
  NtUiLib.Errors in 'NtUtilsUI\NtUtils\NtUiLib\NtUiLib.Errors.pas',
  DelphiUiLib.Reflection.Numeric in 'NtUtilsUI\NtUtils\NtUiLib\RTTI\DelphiUiLib.Reflection.Numeric.pas',
  DelphiUiLib.Reflection in 'NtUtilsUI\NtUtils\NtUiLib\RTTI\DelphiUiLib.Reflection.pas',
  DelphiUiLib.Reflection.Records in 'NtUtilsUI\NtUtils\NtUiLib\RTTI\DelphiUiLib.Reflection.Records.pas',
  DelphiUiLib.Reflection.Strings in 'NtUtilsUI\NtUtils\NtUiLib\RTTI\DelphiUiLib.Reflection.Strings.pas',
  NtUiLib.Reflection.Exceptions in 'NtUtilsUI\NtUtils\NtUiLib\RTTI\NtUiLib.Reflection.Exceptions.pas',
  NtUiLib.Reflection.Types in 'NtUtilsUI\NtUtils\NtUiLib\RTTI\NtUiLib.Reflection.Types.pas',
  NtUiLib.Exceptions.Dialog in 'NtUtilsUI\NtUtils\NtUiLib\GUI\NtUiLib.Exceptions.Dialog.pas',
  NtUiLib.Reflection.AccessMasks in 'NtUtilsUI\NtUtils\NtUiLib\RTTI\NtUiLib.Reflection.AccessMasks.pas';

{$R *.res}

begin
  // Running as a service
  if ParamStr(1) = RESVC_PARAM then
  begin
    SvcxMain(RESVC_NAME, ReSvcRunInSession);
    Exit;
  end;

  // The user delegated us to create a service
  if ParamStr(1) = DELEGATE_PARAM then
  begin
    ReSvcCreateService(ParamStr(2) = RESVC_SYSPLUS_PARAM).RaiseOnError;
    Exit;
  end;

  // Normal mode
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'Token Universe';
  Application.HintHidePause := 20000;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
